# This file was generated by liblab | https://liblab.com/

from formula_one import FormulaOne, Environment

sdk = FormulaOne(base_url=Environment.DEFAULT.value)

result = sdk.drivers.list_of_all_drivers()

print(result)
